* Introduction
  The functions usable wrapped from main are tested and documented
* run
  The main function with name changed
** do_error
   Since the original do_error used exit(1), which is unacceptable for python calling. So I modify it to return to the main function, and add
   #+BEGIN_SRC c
   return 1;
   #+END_SRC
   Just after returning from do_error
